# Generated by Django 5.0.1 on 2024-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="listing",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="listing_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
