# Generated by Django 5.0.1 on 2024-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_listing_alter_contact_listing_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
