# Generated by Django 5.0.1 on 2024-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="landlisting_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
