# Generated by Django 5.0.1 on 2024-02-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_contact_landlisting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="landlisting_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="listing",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="listing_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
