# Generated by Django 5.0.1 on 2024-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bedrooms",
            field=models.IntegerField(blank=True),
        ),
    ]
