# Generated by Django 5.0.1 on 2024-02-24 20:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_alter_listing_photo_1_alter_listing_photo_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="photo_1",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image1"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image2"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image3"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_4",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image4"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_5",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image5"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_6",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image6"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_main",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="main_image"
            ),
        ),
    ]
