# Generated by Django 5.0.1 on 2024-02-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landlistings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlisting",
            name="sqft",
        ),
        migrations.AddField(
            model_name="landlisting",
            name="sqm",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="lot_size",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="photo_main",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="price",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="landlisting",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
